<?xml version="1.0" encoding="utf-8"?><Database Name="log_in" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=UNABIA\SQLEXPRESS;Initial Catalog=log_in;Integrated Security=True" SettingsObjectName="Unabia_Pad.Properties.Settings" SettingsPropertyName="log_inConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.info" Member="infos">
    <Type Name="info">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_log_in" Method="sp_log_in">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_log_inResult">
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_type" Method="sp_type">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>